"""Add nickname to User model

Revision ID: c15a05eaa05a
Revises: d53235340a53
Create Date: 2025-07-24 19:27:19.217033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15a05eaa05a'
down_revision = 'd53235340a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_nickname'), ['nickname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_nickname'))
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
