"""Add many-to-many relationship between NominationTemplate and Criterion

Revision ID: e611d8de5ab8
Revises: 0ce13e0c18f5
Create Date: 2025-07-26 18:39:54.290076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e611d8de5ab8'
down_revision = '0ce13e0c18f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nomination_template_criteria',
    sa.Column('nomination_template_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nomination_template_id'], ['nomination_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nomination_template_id', 'criterion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nomination_template_criteria')
    # ### end Alembic commands ###
